apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sim-log-app
  namespace: meu-projeto
spec:
  # 1) Fonte: seu repositório GitHub
  source:
    type: Git
    git:
      uri: "https://github.com/oborges/sim-log-app.git"
      ref: "main"           # branch a ser usada
  # 2) Estratégia S2I: usa imagem UBI Node.js pública
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/nodejs-14:latest
  # 3) Saída: ImageStreamTag dentro do seu projeto
  output:
    to:
      kind: ImageStreamTag
      name: sim-log-app:latest
  # 4) Triggers: rebuild automático em mudança de código ou config
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: sua-webhook-secret

